### ISSUE TITLE
Support generation of more types of diagrams

### ISSUE THREAD

**Issue by kvaleev** [foliant-docs/foliant#11]
Currently, foliant supports only sequence diagrams from the _blockgiag_ package. We need to have support at least for:

* block diagram
* activity diagram
* logical network diagram

Related issue for that task — #4 

Also it worth thinking having `mermaid` as the diagram engine: https://knsv.github.io/mermaid/#mermaid
It has additional diagram types supported, however, it requires Node.js.

**Comment by moigagoo** [comment]
Thanks to the diagrams processing routine refactor in 0.4.2, adding new diagram backends will be much easier.

To try out the new approach, I've implemented PlantUML support. It took me about 10 minutes including editing the changelog and the whole git flow dance.

I'm closing this issue in favor of particular diagram types feature requests.
