### ISSUE TITLE
Move ref.docx into template folder

### ISSUE THREAD

**Issue by kvaleev** [foliant-docs/foliant#2]
In fact, `ref.docx` file is a template contains Word-styles for pandoc docx generation pipeline; it's name can be confusing though.

So, I suggest to rename `ref.docx` into `doc-template.docx`, move it into `template` folder, and get rid of `reference` folder.

**Comment by moigagoo** [comment]
Sounds good, will do.

Just a small correction though: the folders are `templates` and `references`, not `template` and `reference`.

**Comment by kvaleev** [comment]
Also, it's worth considering to treat docx-templates the same way we treat latex ones: add an additional parameter in `config.json` for them.
