### ISSUE TITLE
LaTex error on image name including "." 

### ISSUE THREAD

**Issue by LaureVergeron** [foliant-docs/foliant#23]
Trying to build a pdf, it crashed on:! LaTeX Error: Cannot determine size of graphic in Zenko/res/zenko.io-logo-color-cmyk.png (no BoundingBox).

The incriminated file name has a dot, can this be handled in the tex file?

**Comment by kvaleev** [comment]
Guess is related to https://tex.stackexchange.com/a/370013

Pretty sure, that adding this to LaTeX template will fix the issue: `\usepackage{grffile}` (https://tex.stackexchange.com/a/10581)

**Comment by LaureVergeron** [comment]
Yes, it does fix it, thanks
