### ISSUE TITLE
Add foliantcache to gitignore?

### ISSUE THREAD

**Issue by kvaleev** [foliant-docs/foliant#3]
Looks like foliantcache folder contains a lot of temporary files that shouldn't be into git repo.

**Comment by moigagoo** [comment]
Yes it should be ignored in any project using Foliant. Should I put it in readme?

**Comment by kvaleev** [comment]
Yes, pls. And also let's add it to project's gitignore: https://github.com/foliant-docs/foliant/blob/master/.gitignore

**Comment by moigagoo** [comment]
Fixed in https://github.com/foliant-docs/foliant/commit/9c9e7fcde956fdfd7397bd1f36ca271e302b53e1
