### ISSUE TITLE
Add support for blockdiag, nwdiag, and actdiag

### ISSUE THREAD

**Issue by moigagoo** [foliant-docs/foliant#4]
This is absolutely trivial since seqdiag is already there.

http://blockdiag.com/en/

**Comment by moigagoo** [comment]
I refactored the diagram processing routine, so adding new diagram backends should be even more trivial now ([ref](26dc41ff29d8ec54da12848f1963cd60403d7a32)).

**Comment by moigagoo** [comment]
Whoever will implement this, please refer to this tutorial: https://github.com/foliant-docs/foliant/wiki/Adding-a-Diagram-Backend

**Comment by Vanderhoof** [comment]
Done:
https://foliant-docs.github.io/docs/preprocessors/blockdiag/
