### ISSUE TITLE
Problem with TOC in SLATE

### ISSUE THREAD

**Issue by AlejandroOteroFreire** [foliant-docs/foliant#56]
Hi, I'm using your tool to create and slate api doc site but I have a problem with the TOC list. It put the _Parameters_, _Response_ and _Response Schema_ at the same level of the method. (**docker-compose run --rm foliant make site -w slate**)
<img width="212" alt="image" src="https://user-images.githubusercontent.com/37369890/92773738-3db0b180-f373-11ea-8447-11ce9edb7344.png">

If I've converted the project to slate source (**docker-compose run --rm foliant make slate**) and run the slate source, it appear OK.
<img width="225" alt="image" src="https://user-images.githubusercontent.com/37369890/92774208-a009b200-f373-11ea-8b65-9027f46e40f8.png">

Do you know where is the problem?

**Comment by moigagoo** [comment]
@AlejandroOteroFreire Hi! Did you solve the issue on your own? Would you mind sharing the solution for the future generations of Foliant users?

**Comment by AlejandroOteroFreire** [comment]
Yes the problem was when you tried to mix content (static and swagger), you must do it is this way:
`chapters:
  - index.md
  - apis.md`
But if you do it is this way it not work:
`chapters:
  - index.md
  _ APIS:
      - apis.md`

Now I'm looking a way to put together few swagger file without repeat the schema part. Do you have some prepocessor to do that?
