### ISSUE TITLE
Show file which contains link to a missing image

### ISSUE THREAD

**Issue by SerjKanunnikov** [foliant-docs/foliant#6]
Foliant stops baking of output if it can't find image file that is referenced in a link somewhere in the sources. 

It would be nice to show which file contains link to a missing image in Terminal log.

**Comment by moigagoo** [comment]
Could you please provide a sample? I can't reproduce it.

When an image is missing, Foliant just skips it.

**Comment by moigagoo** [comment]
Can't reproduce.
