### ISSUE TITLE
Docker baked pdf has no chapter numbering

### ISSUE THREAD

**Issue by abuhtiyarov** [foliant-docs/foliant#7]
while foliant baked pdf with the same template has it.

**Comment by abuhtiyarov** [comment]
basic.tex part describing headers' format:

\titleformat{name=\chapter,numberless}[display]
            {\normalfont\Huge\headingfont}% format
            {\llap{% label
               \chaptertitlename\thechapter\hskip 9pt}#1}%
            {0pt}% horizontal sep
            {}% before


\titleformat{\section}
            {\fontsize{28}{24}\headingfont}%format
            {\makebox[0pt][r]{%
                \headingfontlight\thesection\hskip 9pt}}%
            {0pt}
            {\makebox[\dimexpr\linewidth][l]{%
                  \parbox[t]{\dimexpr\textwidth+\marginparwidth+\marginparsep\relax}
            {\raggedright #1}}}

\titleformat{\subsection}%
            {\fontsize{20}{20}\headingfont}%format
            {\makebox[0pt][r]{%
                \headingfontlight\thesubsection\hskip 9pt}}%
            {0pt}
            {\makebox[\dimexpr\linewidth][l]{%
                  \parbox[t]{\dimexpr\textwidth+\marginparwidth+\marginparsep\relax}
            {\raggedright #1}}}

\titleformat{\subsubsection}%
            {\fontsize{16}{16}\headingfont}%format
            {\makebox[0pt][r]{%
                \headingfontlight\thesubsubsection\hskip 9pt}}%
            {0pt}
            {\makebox[\dimexpr\linewidth][l]{%
                  \parbox[t]{\dimexpr\textwidth+\marginparwidth+\marginparsep\relax}
            {\raggedright #1}}}

\titleformat{\paragraph}%
            {\fontsize{14}{14}\headingfont}%format
            {\makebox[0pt][r]{%
                \headingfontlight\theparagraph\hskip 9pt}}%
            {0pt}
            {\makebox[\dimexpr\linewidth][l]{%
                  \parbox[t]{\dimexpr\textwidth+\marginparwidth+\marginparsep\relax}
            {\raggedright #1}}}

\titleformat{\subparagraph}%
            {\headingfont}%format
            {\makebox[0pt][r]{%
                \headingfontlight\thesubparagraph\hskip 9pt}}%
            {0pt}
            {\makebox[\dimexpr\linewidth][l]{%
                  \parbox[t]{\dimexpr\textwidth+\marginparwidth+\marginparsep\relax}
            {\raggedright #1}}}

**Comment by moigagoo** [comment]
Should be fixed in 0.3.4.

**Comment by moigagoo** [comment]
Fixed in 0.4.5 via cdf9cb79c47f3393681a3b1fcdd2cc2a4c889c8f
