### ISSUE TITLE
foliant init not found

### ISSUE THREAD

**Issue by kkaiser** [foliant-docs/foliant#70]
Hello,

Your [documentation quickstart](https://github.com/foliant-docs/foliant#quickstart) mentions `foliant init` to create the initial structure but installing `foliant` from PyPI results in this error for Python 3.11.2

```bash
foliant init
usage: foliant [-h] [-v] {clean-registry,make,meta} ...
foliant: error: argument {clean-registry,make,meta}: invalid choice: 'init' (choose from 'clean-registry', 'make', 'meta')
```

The installed version is Foliant v.1.0.12 which is weird because it says version 1.0.13 from PyPI.

```bash
$ pip install foliant==1.0.13
Requirement already satisfied: foliant==1.0.13 in ./.venv/lib/python3.11/site-packages (1.0.13)
[...]
$ foliant -v
Foliant v.1.0.12
$ which foliant
.venv/bin/foliant
```

Is this project still maintained?

**Comment by moigagoo** [comment]
Hi! The project is maintained.

Did you install init command?

```
$ pip3 install foliantcontrib.init
```

Learn more about installation options at https://foliant-docs.github.io/docs/installation/

**Comment by kkaiser** [comment]
Thanks for the reply. I missed the sentence, sorry about that
> For the Quickstart, you'll need the [MkDocs backend](https://github.com/foliant-docs/foliantcontrib.mkdocs) and [init CLI extension](https://github.com/foliant-docs/foliantcontrib.init):

Do you have an explanation for the version mismatch?

**Comment by moigagoo** [comment]
@kkaiser it's hard to tell, Python is famous for those type of issues. I'd remove the venv folder and start from scratch and see if it works. Maybe you have 1.0.12 installed previously and it still exposes its binary.
